### ISSUE TITLE
Doc and error msg in the plot

### ISSUE THREAD

**Issue by j23414** [arendsee/rmonad#20]
Given a monad `m`, why can't I plot the documentation and error messages? Am I missing something?

The following commands work individually:

```
plot(m, label=get_doc)
plot(m, label=get_error)
```

![01](https://user-images.githubusercontent.com/1077254/50426988-11809480-0861-11e9-8db4-c05091352fec.png)

But when I use

```
plot(m,label=paste(get_doc,get_error,sep=":"))
```

I get error msg

```
Error in paste(get_doc, get_error, sep = ":") : 
  cannot coerce type 'closure' to vector of type 'character'
```

**Comment by j23414** [comment]
Works, thanks!

![03](https://user-images.githubusercontent.com/1077254/50430977-d6945600-088c-11e9-97d7-57451f96a6df.png)

**Comment by arendsee** [comment]
Cool! Merry Christmas!

Though it would make a nicer diagram if we could get nodes to scale independently with the size of the text. I used to use DiagrammeR by default in the graphs. That made way prettier plots. Maybe we could add it back?
